### ISSUE TITLE
Question: Fabric or Forge?

### ISSUE THREAD

**Issue by Arthurmeade12** [yungnickyoung/YUNGs-Better-Dungeons#1]
If this mod is for Fabric, is it 1.16.5 or 1.17? 
Thanks!

**Comment by Slimation** [comment]
From the looks of things Yung usually releases the forge version first and later on releases the fabric version. Depending on if Yung makes a Fabric version, you would probably see it update to 1.17 sooner or perhaps on the same day, but if Forge releases first it would take a while for it to update since Forge for 1.17 isn't out yet. However, take everything I say here with a grain of salt, I ain't the big brain player behind the mods so I don't really know all of this for certain.

**Comment by yungnickyoung** [comment]
Forge 1.16 first, then Fabric 1.16. 1.17 will likely be skipped.
