### ISSUE TITLE
Catacombs and spider nests entrances sometime generate in rivers.

### ISSUE THREAD

**Issue by Wedge1453** [yungnickyoung/YUNGs-Better-Dungeons#10]
![2021-08-26_00 19 25](https://user-images.githubusercontent.com/76813383/131979470-3eb42ffa-7aff-4c2c-b58c-311741b5d6da.png)

**Comment by yungnickyoung** [comment]
Closing since this should be fixed as of recent versions. It's still possible for dungeons to generate in water, but they shouldn't generate in river and ocean biomes (at least, not vanilla biomes, anyway). I don't see a reason to prevent them from generating in water at all - it's janky, but kinda cool, lol.
