### ISSUE TITLE
Compatibility with Apotheosis

### ISSUE THREAD

**Issue by predundant** [yungnickyoung/YUNGs-Better-Dungeons#25]
Better Dungeons disables vanilla dungeons by default which prevents Apotheosis boss dungeons and rogue spawners from generating.  Re-enabling vanilla dungeons in the better dungeons config fixes this.  Hoping Apotheosis can be whitelisted or something so its features can generate while still having vanilla dungeons disabled.

**Comment by yungnickyoung** [comment]
I think providing the config option is sufficient. If other mod devs want built-in compat out-of-the-box, they can add checks for biomes without structures and add them where necessary. It's probably best if structures are simply added to biomes, rather than checking specifically for the presence of a structure.
