### ISSUE TITLE
[SUGGESTION] Blacklist of Biomes to not spawn dungeons in

### ISSUE THREAD

**Issue by Shazuli** [yungnickyoung/YUNGs-Better-Dungeons#37]
***Hi***

It would be nice with a config to blacklist certain biomes from generating dungeons. I think it looks weird with spider dungeons spawning in oceans:
![2022-05-29_12 21 41](https://user-images.githubusercontent.com/9884180/170863223-5053b4df-0eb7-47cd-a803-f6b3042dd76b.png)

**Comment by Jukabofy** [comment]
I'm sure that's possible with datapacks

**Comment by Jukabofy** [comment]
since 1.18.2 you have to use Datapacks of course

**Comment by yungnickyoung** [comment]
Starting with 1.18, I believe this should no longer happen since structures get to specify exactly which biomes they spawn in. Note that there is still a chance structures spawn in water, if the water is still technically in a non-ocean biome - this behavior is intended and there's no plan to change it atm.
